<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
define('PATH', realpath(dirname(__FILE__) . '/../framework'));
spl_autoload_register(
	function($class) {
		static $classes = null;
		if ($classes === null) {
			$classes = array(
				'Eve\Util\File'					=> '/Util/File.php',
				'Eve\Util\Strings'				=> '/Util/Strings.php',
				'Eve\Util\Mobile'				=> '/Util/Mobile.php',
				'Eve\Util\Arrays'				=> '/Util/Arrays.php',
				'Eve\Util\Map'					=> '/Util/Map.php',
				'Eve\Util\Date'					=> '/Util/Date.php',
				'Eve\Util\Input'				=> '/Util/Input.php',
				'Eve\Util\Upload'				=> '/Util/Upload.php',
				'Eve\Filter\Strings'			=> '/Filter/Strings.php',
				'Eve\Session\Apc'				=> '/Session/Apc.php',
				'Eve\Session\File'				=> '/Session/File.php',
				'Eve\Session\Db'				=> '/Session/Db.php',
				'Eve\Session\DriverInterface'	=> '/Session/DriverInterface.php',
				'Eve\Session\Memcache'			=> '/Session/Memcache.php',
				'Eve\Session\Cookie'			=> '/Session/Cookie.php',
				'Eve\Session\SweeperInterface'	=> '/Session/SweeperInterface.php',
				'Eve\Cache\File'				=> '/Cache/File.php',
				'Eve\Cache\File\Exception'		=> '/Cache/File/Exception.php',
				'Eve\Cache\Memcache\Exception'	=> '/Cache/Memcache/Exception.php',
				'Eve\Cache\Memcache'			=> '/Cache/Memcache.php',
				'Eve\Curl\Json'					=> '/Curl/Json.php',
				'Eve\Database\Mysql'			=> '/Database/Mysql.php',
				'Eve\Database\Pdo'				=> '/Database/Pdo.php',
				'Eve\Database\Exception'		=> '/Database/Exception.php',
				'Eve\Mvc\ControllerException'	=> '/Mvc/ControllerException.php',
				'Eve\Mvc\Component'				=> '/Mvc/Component.php',
				'Eve\Mvc\AbstractController'	=> '/Mvc/AbstractController.php',
				'Eve\Mvc\Autoloader'			=> '/Mvc/Autoloader.php',
				'Eve\Mvc\SplClassLoader'		=> '/Mvc/SplClassLoader.php',
				'Eve\Mvc\DispatcherException'	=> '/Mvc/DispatcherException.php',
				'Eve\Mvc\Event'					=> '/Mvc/Event.php',
				'Eve\Mvc\View'					=> '/Mvc/View.php',
				'Eve\Mvc\Request'				=> '/Mvc/Request.php',
				'Eve\Mvc\Request\Method'		=> '/Mvc/Request/Method.php',
				'Eve\Mvc\Config'				=> '/Mvc/Config.php',
				'Eve\Mvc\ViewException'			=> '/Mvc/ViewException.php',
				'Eve\Mvc\Error'					=> '/Mvc/Error.php',
				'Eve\Mvc\Response'				=> '/Mvc/Response.php',
				'Eve\Mvc\Dispatcher'			=> '/Mvc/Dispatcher.php',
				'Eve\Mvc\Router\AbstractRouter'	=> '/Mvc/Router/AbstractRouter.php',
				'Eve\Mvc\Router\Simple'			=> '/Mvc/Router/Simple.php',
				'Eve\Mvc\Router\RouterInterface'=> '/Mvc/Router/RouterInterface.php',
				'Eve\Mvc\RequestException'		=> '/Mvc/RequestException.php',
				'Eve\Mvc\SplAutoLoader'			=> '/Mvc/SplAutoLoader.php',
				'Eve\Mvc\Exception'				=> '/Mvc/Exception.php',
				'Eve\Mvc\ErrorException'		=> '/Mvc/ErrorException.php',
				'Eve\Benchmark'					=> '/Benchmark.php',
				'Eve\Crypter'					=> '/Crypter.php',
				'Eve\Database'					=> '/Database.php',
				'Eve\EveBase'					=> '/EveBase.php',
				'Eve\Eve'						=> '/Eve.php',
				'Eve\Exception'					=> '/Exception.php',
				'Eve\Filter'					=> '/Filter.php',
				'Eve\Flash'						=> '/Flash.php',
				'Eve\Logger'					=> '/Logger.php',
				'Eve\Mail'						=> '/Mail.php',
				'Eve\PasswordHash'				=> '/PasswordHash.php',
				'Eve\Session'					=> '/Session.php',
				'Eve\Validate'					=> '/Validate.php',
			);
		}
		if (isset($classes[$class])) {
			require \PATH . $classes[$class];
			return true;
		}

		return false;
	}

);
// @codeCoverageIgnoreEnd

